# Generated by Django 6.0.5 on 2026-06-07 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма расходов')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finance.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма доходов')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='finance.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Доход',
                'verbose_name_plural': 'Доходы',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название кошелька')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='finance.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Кошелёк клиента',
                'verbose_name_plural': 'Кошельки клиентов',
            },
        ),
    ]
