# Generated by Django 6.0.5 on 2026-06-10 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense_category_expense_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.CharField(default='Без категории', max_length=100, verbose_name='Категория доходов'),
        ),
        migrations.AddField(
            model_name='income',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='finance.wallet', verbose_name='Кошелёк'),
        ),
    ]
