# Generated by Django 6.0.5 on 2026-06-10 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_income_category_income_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название цели')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание цели')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='finance.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
            },
        ),
    ]
